site_name: TRON Documentation
site_url: https://tronprotocol.github.io/documentation-en/
repo_url: https://github.com/tronprotocol/documentation-en

nav:
    - Home: index.md
    - Introduction:
        - Repository: introduction/index.md
        - DPoS: introduction/dpos.md
        - Overview: introduction/overview.md
    - API:
        - HTTP API: api/http.md
        - RPC API: api/rpc.md
    - Mechanism & Algorithm:
        - SR and Committee: mechanism-algorithm/sr.md
        - TRC-10: mechanism-algorithm/trc10.md
        - Account Model: mechanism-algorithm/account.md
        - Resource Model: mechanism-algorithm/resource.md
        - Decentralized Exchange: mechanism-algorithm/dex.md
        - Multi-Signature: mechanism-algorithm/multi-signatures.md
        - Shielded TRC20 Contract: mechanism-algorithm/shielded-TRC20-contract.md
        - System Contracts:  mechanism-algorithm/system-contracts.md
    - Architecture:
        - Network: architecture/network.md
        - Database: architecture/database.md
        - Event Subsystem: architecture/event.md
    - Smart Contract:
        - TVM: contracts/tvm.md
        - Compiler: contracts/compiler.md
        - Contract: contracts/contract.md
        - TRC-20: contracts/trc20.md
    - Developers:
        - Official Public Nodes: developers/official-public-nodes.md
        - Deployment: developers/deployment.md
        - Run FullNode in IDEA: developers/run-in-idea.md
        - Run Lite FullNode: developers/litefullnode.md
        - Leveldb Startup Optimization Plugins: developers/archive-manifest.md
        - Resources: developers/resources.md
        - Contribution: developers/contribution.md
        - Incentive Policy: developers/incentives.md
        - Java-Tron: developers/java-tron.md
        - TIPs: developers/tips.md
        - Advanced Configuration: developers/advanced-configuration.md
        - Contact Us (GPG Key): developers/gpg.md
    - Clients:
        - Wallet-cli: clients/wallet-cli.md
        - TronGrid: clients/tron-grid.md
    - Releases:
        - Binary Integrity Check: releases/index.md
    - FAQ: faq/index.md
    - Glossary: glossary.md

theme: readthedocs
extra_javascript:
    - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
markdown_extensions:
    - admonition
    - footnotes
    - codehilite
    - toc:
        permalink: true
    - pymdownx.arithmatex
    - pymdownx.tilde
    - pymdownx.tasklist
    - pymdownx.superfences
